name: diamond
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - scikit-learn>=1.0.0
  - nibabel>=3.2.0
  - h5py>=3.6.0
  - tqdm>=4.62.0
  - pytest>=7.3.1
  - seaborn>=0.11.2
  - black>=23.3.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - mypy>=1.3.0
  - sphinx>=6.2.1
  - pytest-xdist>=3.3.1
  - pytest-cov>=4.1.0
  - pip:
    - pydicom>=2.2.0
    - dicom2nifti>=2.3.0
    - torch>=1.10.0
    - torchvision>=0.11.0
    - torchio>=0.18.0
    - monai>=0.9.0
    - wandb>=0.15.0
    - hypothesis>=6.72.1
    - zenml>=0.40.0
    - sphinx-rtd-theme>=1.2.1
    - pytest-benchmark>=4.0.0
    - tox>=4.6.0
    - pandas-stubs>=1.2.0
    - types-requests>=2.27.0
    - einops>=0.3.2
    - requests
